# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: myapp

---
# nodeport service
apiVersion: v1
kind: Service
metadata:
  name: myapp-webapp
  namespace: myapp
spec:
  type: NodePort
  selector:
    app: myapp-webapp
  ports:
  - name: http-web-port
    port: 8000
    targetPort: 8000
    nodePort: 30080
---
# myapp deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: myapp-webapp
  name: myapp-webapp
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      name: myapp-webapp
      labels:
        app: myapp-webapp
        env: production
    spec:
      containers:
      - name: myapp-webapp-container
        image: $image
        resources:
          requests:
            cpu: "400m"
            memory: "400Mi"
          limits:
            # cpu: "900m"
            memory: "500Mi"   
        ports:
        - name: http-web-port
          containerPort: 8000
        imagePullPolicy: Always
        env:
        - name: DJANGO_ENV
          value: "prod"
        - name: BASE_URL
          value: "https://myapp.dev"          
        - name: DATABASE_NAME
          value: "mydb"
        - name: DATABASE_USER
          value: "myuser"
        - name: DATABASE_PASSWORD
          value: "mypassword"
        - name: DATABASE_HOST
          value: "x.x.x.x"
        - name: DATABASE_PORT
          value: "5432"        
        - name: EMAIL_BACKEND
          value: "django.core.mail.backends.console.EmailBackend"
        - name: REDIS_HOST
          value: "x.x.x.x"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_USERNAME
          value: 
        - name: REDIS_PASSWORD
          value: 
        - name: CELERY_BROKER_DB
          value: "2" 
        - name: REDIS_DB
          value: "1"       
---